name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  ClientSecret: Secret

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
  test:
    name: integration test
    runs-on:
      - linux


    steps:
      - name: echo clientSecret
        run: echo "${{ env.ClientSecret }}"
