name: Test workflow
on: push

env:
  ClientSecret: ${{ secrets.ACCESS_TOKEN }}

defaults:
  run:
    working-directory: .

jobs:
  test:
    name: integration test
    runs-on:
      - ubuntu-latest

    steps:
      - name: echo clientSecret
        run: |
            echo ${{ env.clientSecret }}
      - name: manifest Version
        uses: deef0000dragon1/json-edit-action/@v1
        env:
          KEY: name
          VALUE: komal
          FILE: file.json

