name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  ClientSecret: ${{ secrets.ACCESS_TOKEN }}

jobs:
  test:
    name: integration test
    runs-on:
      - ubuntu-latest
    steps:
      - name: echo clientSecret
        run: |
          echo "${{ env.ClientSecret }}"
      - name: update file.json    
        uses: jossef/action-set-json-field@v1
        with: 
          file: file.json
          field: abc
          value: ${{ secrets.ACCESS_TOKEN }}
      