name: Test workflow
on: push

env:
  ClientSecret: ${{ secrets.ACCESS_TOKEN }}

defaults:
  run:
    working-directory: .

jobs:
  test:
    name: integration test
    runs-on:
      - ubuntu-latest


    steps:
      - name: echo clientSecret
        run: |
            echo ${{ env.clientSecret }}
      - name: add value to field
        uses: jossef/action-set-json-field@v1
        with:
          file: environment.json
          field: abc
          value: ${{ env.ClientSecret }}